### ISSUE TITLE
Generator for Dell - 3A5B, 1F5A, 1F66, 6FF1, With Hint key, Hint code 8/16, PPID-23

### ISSUE THREAD

**Issue by mikrovr** [bacher09/pwgen-for-bios#10]

**Comment by mikrovr** [comment]
Open to all comments, why make them public?

**Comment by mikrovr** [comment]
## Open to all comments, why make them public?

**Comment by mikrovr** [comment]
## Open to all comments, why make them public?
## His suggestion, as could be done, sulfix 1D3B is free, it is still being sold on Ebay ..

**Comment by drgn997** [comment]
You should learn from Dogber1, he made available many algorithms, but then stop releasing them when he saw many users selling his work at eBay and other places.

**Comment by mikrovr** [comment]
**drgn997**
So you believe it would be better never make them public? That would be your honest opnion?
