### ISSUE TITLE
HP BIOS EXTRACTING ISSUE

### ISSUE THREAD

**Issue by vishnu79** [bacher09/pwgen-for-bios#101]
Hi guys https://ftp.hp.com/pub/softpaq/sp101001-101500/sp101033.exe

I how to extract theselike bios........  Please help me to extract this file👇👇👇

https://ftp.hp.com/pub/softpaq/sp101001-101500/sp101033.exe

**Comment by bacher09** [comment]
Sorry but this isn't support forum, it's an issue tracker. Also this model should be already supported.
