### ISSUE TITLE
Fresh Generated Samsung 44 Digit ( HEX to TEXT Converted ) Reverse Engineering

### ISSUE THREAD

**Issue by B0mberManFanky** [bacher09/pwgen-for-bios#103]
AEF13EE53CD1B453CACE161579950D3A3696A1835302   = 1984
59F72F85239CC9DB6239DEDDC5C4CDB43A37D5533003 = 123987
2BC387ACAD6DFA9ABD0DE3B20EE427B5A907CC32C189 = vito12
351EF13822577610E4ED863695BD6CB7B356A5227185     = artis12
D78EF5B5CA236F4869662339D9912C39B727D50BB285    = justin
DF6E02658349EC455407A5CD60666AC01B26C0465004    = 25170537
7856AC492A91B6A343B267680D4CDC016C8906194004   = 15172431
0C2D3C17293624ABAC569559CACA5E8C97E5BCE5D206  = //////eeeeee
F0AC97598FCB9BEB0E8C69478055833466C9E61BD102     = 6793
22D8DBEF1B9A2D24AAC8663A58B1AC5AB6AD2D5AF105 = belue
0E45ED5D2EF8949498AF1A9C2763726091E4850D1105     = Car2092961
8DD4D28455C8CDD06C4372190E9B264D1927E6C9F107   = 97925178294647
54574AAD6A8B1B9353F6FA66DCD2DA91B06DBD8E3204  = tokadmin
BF5EC2647227EDC493BDBBB8C4BD0DB53DE6BD533083   = jonzkho
DED9EA70EA68EB1D3CDDB32C05CCE6391807D59B8083   = sup0r73
B6C5525D15BCA963277178ED150EA3A968994698B382     = 123456
525052DF4524459125E750FA97B7DCBDB98DA5EE7303      = eillsom
8DD5CFD4ADBC740A9EEF381383EADE621C23CCA10302    = 4898
AEF53EE53CD1B453CACE163989950D3A3696A1835306      = philthebrave
2D2FB35C18B2B4846F1F989846036E6CA968E4C87005        = 2945670211

**Comment by bacher09** [comment]
This already implemented it in 4bd66069e336170fd3e4be42e55686b66f0ba98f, thanks for providing this testing data. However I wanted to admit that some keys in this list is wrong. And some probably generated with another algorithm (or simply invalid).

Here's python script that decodes these passwords and encodes them back (to check if result would be the same):

```python
#!/usr/bin/env python3
TABLE = [
    3, 6, 3, 1, 6, 7, 7, 7, 2, 6, 4, 3, 4, 6, 1, 7, 2, 1, 7, 7,
    5, 3, 3, 1, 2, 3, 1, 2, 1, 7, 4, 7, 6, 2, 4, 4, 1, 6, 1, 5,
    6, 6, 7, 5, 7, 7, 4, 3, 1, 1, 1, 6, 3, 2, 7, 3, 7, 3, 7, 3,
    5, 6, 4, 1, 1, 3, 6, 6, 1, 4, 3, 7, 6, 7, 5, 3, 6, 7, 6, 3,
    1, 3, 5, 7, 5, 6, 2, 2, 7, 5, 7, 1, 2, 3, 2, 1, 6, 4, 5, 3,
]


def rol(val, shift):
    return ((val << shift) & 0xFF) | (val >> (8 - shift))


def ror(val, shift):
    return ((val << (8 - shift)) & 0xFF) | (val >> shift)


def lock_algo(input_data, seconds):
    output = bytearray(22)
    output[0] = len(input_data) << 3
    output[1] = seconds
    key = (seconds % 5) * 20
    for i, c in enumerate(input_data):
        shift = TABLE[key + i]
        output[i + 2] = ror(ror(c, 4), shift)

    seed = seconds
    for i in range(len(input_data), 20):
        # standard lcg
        seed = (seed * 0x343fd + 0x269ec3) & 0xFFFFFFFF
        val = (seed >> 0x10) & 0x7fff
        shift = TABLE[key + i]
        output[i + 2] = ror(ror(val % 253 + 1, 4), shift)

    return output.hex()[::-1].upper()


def unlock_algo(input_data):
    hash_data = bytes.fromhex(input_data[::-1])
    pwd_len = hash_data[0] >> 3
    key = hash_data[1] % 5
    output = bytearray()
    for i in range(0, pwd_len):
        shift = TABLE[key * 20 + i]
        sym = rol(rol(hash_data[i + 2], shift), 4)
        output.append(sym)
    return output


def test_algorithm(input_data):
    hash_data = bytes.fromhex(input_data[::-1])
    seconds = hash_data[1]
    pwd = unlock_algo(input_data)
    serial = lock_algo(pwd, seconds)
    if input_data != serial:
        print("{0} vs {1}".format(input_data, serial))


if __name__ == '__main__':
    test_algorithm("AEF13EE53CD1B453CACE161579950D3A3696A1835302")
    test_algorithm("59F72F85239CC9DB6239DEDDC5C4CDB43A37D5533003")
    test_algorithm("2BC387ACAD6DFA9ABD0DE3B20EE427B5A907CC32C189")
    test_algorithm("351EF13822577610E4ED863695BD6CB7B356A5227185")
    test_algorithm("D78EF5B5CA236F4869662339D9912C39B727D50BB285")
    test_algorithm("DF6E02658349EC455407A5CD60666AC01B26C0465004")
    test_algorithm("7856AC492A91B6A343B267680D4CDC016C8906194004")
    test_algorithm("0C2D3C17293624ABAC569559CACA5E8C97E5BCE5D206")
    test_algorithm("F0AC97598FCB9BEB0E8C69478055833466C9E61BD102")
    test_algorithm("22D8DBEF1B9A2D24AAC8663A58B1AC5AB6AD2D5AF105")
    test_algorithm("0E45ED5D2EF8949498AF1A9C2763726091E4850D1105")
    test_algorithm("8DD4D28455C8CDD06C4372190E9B264D1927E6C9F107")
    test_algorithm("54574AAD6A8B1B9353F6FA66DCD2DA91B06DBD8E3204")
    test_algorithm("BF5EC2647227EDC493BDBBB8C4BD0DB53DE6BD533083")
    test_algorithm("DED9EA70EA68EB1D3CDDB32C05CCE6391807D59B8083")
    test_algorithm("B6C5525D15BCA963277178ED150EA3A968994698B382")
    test_algorithm("525052DF4524459125E750FA97B7DCBDB98DA5EE7303")
    test_algorithm("8DD5CFD4ADBC740A9EEF381383EADE621C23CCA10302")
    test_algorithm("AEF53EE53CD1B453CACE163989950D3A3696A1835306")
    test_algorithm("2D2FB35C18B2B4846F1F989846036E6CA968E4C87005")
```

As you can see 2 items from this list fail to produce same result.

**Comment by B0mberManFanky** [comment]
Excellent

**Comment by mohamedxp** [comment]
toshiba challenge code any help Mr B0mberManFanky
this is my email : moh12369@yahoo.fr
thank you

**Comment by jesss4444** [comment]
Could you help me a little with the Toshiba challenge code generator please amd_fx6100asus@hotmail.com

**Comment by jafasbay** [comment]
Toshiba response code generator pls. jafasbay@gmail.com . only for me pls..
