### ISSUE TITLE
Bios pass for acer aspire 3 unlock password 2079580927

### ISSUE THREAD

**Issue by iguzman-sys** [bacher09/pwgen-for-bios#106]
I need the password to enter the bios please.
Acer aspire 3 A315-31-C3CC

**Comment by aditya11ttt** [comment]
91a708d84356b000

**Comment by iguzman-sys** [comment]
Thanks but the password most be 12 characters, this are 16 characters and I could not enter to

**Comment by iguzman-sys** [comment]
Omg yes it work, thanks sooooooo much, I appreciate a lot your help..

**Comment by bacher09** [comment]
This already supported in 327fa5f8154e2c3d9f36b63f892d87685161c3b3.
