### ISSUE TITLE
Need unlock code for HP Pavilion 13-s168nr x360 Convertible

### ISSUE THREAD

**Issue by xdemonx14** [bacher09/pwgen-for-bios#107]
(i 59264321) I dont know what else information you need but thats the disabled code its spitting out and im trying to get this laptop working for my uncle. I’ve had for 2 days already and I even tried the thing with cmos battery. I read that worked for some.

**Comment by aditya11ttt** [comment]
64839764

**Comment by bacher09** [comment]
This already implemented in 1580bf4ac103e54b3bd5741556f7f795e0ddecd1.
