### ISSUE TITLE
Dell Precision 5540 bios unlock codes not working

### ISSUE THREAD

**Issue by demdante** [bacher09/pwgen-for-bios#117]
Hello.  So, I have a dell precision 5540 which I would have thought had a supported BIOS, since the bios series is BF97, but the generated password for my device failed to unlock the BIOS.   

### General information

* **Vendor**: Dell
* **Model**: Precision 5540
* **Firmware version**:     

![image](https://user-images.githubusercontent.com/64720591/90335484-e3673f80-dfc4-11ea-95d0-7a64864000ae.png)

### Photo

It also would be helpful if you post a photo of your locked screen (with generated code, `system
disabled` message) for example like [here][photo-sample]. You can skip this if there are multiple
images with exact same message.

![image](https://user-images.githubusercontent.com/64720591/90335443-9f743a80-dfc4-11ea-9486-8eb57e0b77a5.png)

**Comment by qasimtoep01** [comment]
Password is:  e2pJzmkr32r2k5r6

**Comment by bacher09** [comment]
[Website](https://bios-pw.org/) should generate `e2pJzmkr32r2k5r6` password, is it working ? If not than please mention this, I'm closing this for now.
