### ISSUE TITLE
I need help with this too, it has been driving me crazy. I have the same computer HP Envy x360 convertible M6. mine is i 63497888. please help.

### ISSUE THREAD

**Issue by henish191** [bacher09/pwgen-for-bios#119]
**NOTE**: *You should select this option if you are going to request support for new unlock
algorithm or existing one didn't worked for you*.

**IMPORTANT**: before creating a new issue first check if there is any existing one with same model
or algorithm request, in that case you'd better add information to that particular issue (your
laptop model, BIOS version, screen photo, etc). 

Please replace `[VENDOR]` in a title with your laptop vendor (e.g. dell, hp, acer) and `[MODEL]`
with model, also you can specify extra information in `[algorithm info]` if you can, otherwise just
remove it from a title.

Please specify following information:

### General information

* **Vendor**: specify here your laptop manufacturer (e.g. dell, hp, acer, etc.)
* **Model**: your laptop model (please be as specific as possible)
* **Firmware version**: version of your BIOS firmware, it also good if you can specify firmware
  release date.

### Photo

It also would be helpful if you post a photo of your locked screen (with generated code, `system
disabled` message) for example like [here][photo-sample]. You can skip this if there are multiple
images with exact same message.

**Don't expect on immediate response**, your issue might help someone other who would face such
issue in a feature but not necessarily you. I'd suggest you to contact your vendor support, cause
this should be much faster channel.

[photo-sample]: https://github.com/bacher09/pwgen-for-bios/issues/108#issue-638364581

**Comment by qasimtoep01** [comment]
i 63497888

Password is:  54206627

**Comment by bacher09** [comment]
Hey this is not support forum, but a bug tracker, first you need to try your code on [website](https://bios-pw.org/) and your model should be supported there.
