### ISSUE TITLE
Dell Latitude E6430 "7K9VYW1" Bios version A09

### ISSUE THREAD

**Issue by euclidean2** [bacher09/pwgen-for-bios#120]
I'm trying to update the BIOS but it's asking for the password. I used the serial number (7K9VYW1) which brought up nothing and the express service code "16463407969" which brought up "yyyyy7nn" which didn't work
![1](https://user-images.githubusercontent.com/72683373/95671804-cb88e380-0b4f-11eb-85f4-ec2fe913af43.PNG)
![2](https://user-images.githubusercontent.com/72683373/95671806-cc217a00-0b4f-11eb-9951-1ae9fed77edb.PNG)

**Comment by euclidean2** [comment]
used wrong serial number, found the correct one and it worked

**Comment by euclidean2** [comment]
found the actual serial number 7K9VYW1-1D3B. but neither of the codes worked

**Comment by qasimtoep01** [comment]
7K9VYW1-1D3B

Password is:  udGDnwyTDuNhkubn

u - uniform ( lowercase )
d - delta ( lowercase )
G - GOLF ( UPPERCASE )
D - DELTA ( UPPERCASE )
n - november ( lowercase )
w - whisky ( lowercase )
y - yankee ( lowercase )
T - TANGO ( UPPERCASE )
D - DELTA ( UPPERCASE )
u - uniform ( lowercase )
N - NOVEMBER ( UPPERCASE )
h - hotel ( lowercase )
k - kilo ( lowercase )
u - uniform ( lowercase )
b - bravo ( lowercase )
n - november ( lowercase )
IMPORTANT!

After typing your password, to accept press left CTRL key and holding this key Press Enter twice

**Comment by euclidean2** [comment]
ctrl+enter worked for me, thx
