### ISSUE TITLE
Samsung ATIV bios password recovery

### ISSUE THREAD

**Issue by kcudnik** [bacher09/pwgen-for-bios#13]
Is there a way to recover password from samsung ativ?

Samsung Ativ NP940X3G-S03US
S/N: JKQQ91IF900061L
SYSTEM DISABLED:47C6BC8C8ECC259534A56712F0F664640BE05916103

system disabled code seems to be very long and don't match any of those listed on web page :(
Can you help me with that please?

**Comment by mikrovr** [comment]
**I always say, new codes are coming ...
dishonest sellers with programmers are dead**

**Comment by mikrovr** [comment]
@kcudnik
Friend, could send a screenshot of the password to my email

Samsung Ativ NP940X3G-S03US 
S / N: JKQQ91IF900061L 
SISTEMA DE DEFICIENTES: 47C6BC8C8ECC259534A56712F0F664640BE05916103

mikrovr@gmail.com

**Comment by kcudnik** [comment]
Thanks, i sent photos to @

**Comment by klai93** [comment]
Hi I know this is an old post, but just wanted to ask anyways -- were you able to recover from the locked BIOS on this machine?

I have the same issue with my Samsung Ativ NP940X3G-S03US -- but I haven't been able to find any solutions for some time now. Any help would be great!

**Comment by kcudnik** [comment]
Unfortunately i was not able to unlock my bios :/ I ended up taking out ssd and install new system on it on externall machine. As i contacted Samsung, the only way according to them is to physically send notebook to them for "some kind chip replacement" on mother board (yea right)

**Comment by shayanaboutalebi1** [comment]
That’s actually completely true, they have to either replace or remove and flash the bios chip and replace it as there are no brag connectors on the board that I can find so they weren’t lying as far as I can tell

**Comment by kcudnik** [comment]
I forgot about this issue, but in January 2018 i found a guy on ebay that offers recovery for $20, send him system disable code that was displayed on the screen and in 5 min he send me back generated password that unlocked my laptop bios. Problem solved in 5 min!!! without any hassle. 

Yes, THEY WERE LYING, kind of, those system disable code were designed for password reset/recovery, they contain internal information to generate new password for bios unlock. And since this is samsung laptop service, they "should" have access to those password reset software tools, maybe they actually don't have access to this software, and yes physically replacing bios chip that is not locked would also solve the issue, but going this path is specifically designed to drain your money and make you mentally down:
* you need to pay for shipping laptop to them
* you need to pay for procedure, labor etc (starts from $100)
* if you leave ssd inside laptop, they will probably wipe it out "just for in case"
* you are risking damage of your mother board, since this chip replacement is manual, and humans make mistakes 
* you need to pay for shipping back from them
* you loose access to your laptop for a few weeks (even if everything is working, just bios is locked)

In total about $200 for all costs if you are in the US. I'm happy i found ebay offer for 1/10 of that, which proves that unlocking bios is possible without any hardware replacement and without leaving home. And Samsung can definitely offer that service, but they don't. It's more profitable for them to not offer that, leave user locked, and possibly pay for new laptop. 
Since 2015, I'm still using that laptop, i just replaced original ssd (128G) for 1T size, everything works fine, and quality is really good. In 5 years is just opened it twice for ssd replacement and clean dust bunnies with compressed air.

And i see now that this system error code support was added to this repo: https://github.com/bacher09/pwgen-for-bios/commit/4bd66069e336170fd3e4be42e55686b66f0ba98f

**Comment by kcudnik** [comment]
@klai93 they added solution for my/your problem to this repo, which is available online https://bios-pw.org/ if you still looking for it :)

**Comment by klai93** [comment]
@kcudnik 

Wow, yes the new solver works on the long strings! It churned out my original intended password, but showed that I had always been missing 1 character in the middle from a missed keystroke.

And yeah, Samsung had pointed it to a third-party vendor to repair - who quoted me at least $400-500 for replacing the whole motherboard on an aging machine. The whole process was never worth it to me, like you said. I'd just about forgotten this laptop - but I have it booted up again, and it's no longer that $1,000 paperweight.

Thanks for taking the time to reply and remind me. Happy holidays.
