### ISSUE TITLE
HP:Envy Ts 17 notebook pc. suffix "i-" . 8 digits code

### ISSUE THREAD

**Issue by izumrudik** [bacher09/pwgen-for-bios#133]
###
nothing worked for me

### General information

HP ENVY TS 17 Notebook PC
F.71 - bios version

### Photo

![image](https://user-images.githubusercontent.com/60283525/114283051-69eaf880-9a50-11eb-87c7-289ef0436e67.png)

![image](https://user-images.githubusercontent.com/60283525/114283055-740cf700-9a50-11eb-94ab-d5bf5e43f764.png)

**Comment by 1024kbdotcodotnz** [comment]
55817952 
or
77180535

**Comment by izumrudik** [comment]
![image](https://user-images.githubusercontent.com/60283525/121805847-afe15a00-cc55-11eb-8fed-58352352616d.png)
55817952 worked, but how you get it?

**Comment by izumrudik** [comment]
I get it:
![image](https://user-images.githubusercontent.com/60283525/121805969-5b8aaa00-cc56-11eb-87fc-910c47a58f8e.png)
But it wasn't clear.
