### ISSUE TITLE
[DELL]: [Inspiron M5110] [Inspiron M511R]

### ISSUE THREAD

**Issue by MRM5110** [bacher09/pwgen-for-bios#139]
Dell Inspiron M5110/Inspiron M511R
Service Tag: 4DS6HR1

Problem: Admin Setup Password in BIOS

I already used all the codes on the site and tried to enter it more than three times. It seems all the passwords provided did not work. Can you provide a new set of passwords for this model?

Firmwire Model:
![image](https://user-images.githubusercontent.com/84322431/118481838-80b6f600-b746-11eb-870a-de934aa99f89.png)

Other information:
![image](https://user-images.githubusercontent.com/84322431/118481976-b4921b80-b746-11eb-9b0b-265ffbfcf787.png)

**Comment by imranromi** [comment]
> 4DS6HR1
Password : 570B9582

**Comment by MRM5110** [comment]
> > 4DS6HR1
> > Password : 570B9582

Yep this is the password thank you!
