### ISSUE TITLE
[Dell]: [Inspiron 3537] No codes worked

### ISSUE THREAD

**Issue by asheroto** [bacher09/pwgen-for-bios#149]
### General information

* **Vendor**: Dell
* **Model**: Inspiron 3537
* **Firmware version**: A12, September 24, 2019

### Photo

![image](https://user-images.githubusercontent.com/49938263/131560721-526994af-0890-46d2-9181-3dd1763d62ab.png)

### Info

Inside of the BIOS is says `InsydeH20 Setup Utility` at the top, although it is stock Dell Inspiron 3537 firmware. I tried all suffixes under Dell. No apparent 8 decimal digit code available for the Insyde20 codes.

Tried Enter and Ctrl+Enter.  It appears that just Enter is the expected input.

Some of the generated codes such as this one are too long for the password input field...

![image](https://user-images.githubusercontent.com/49938263/131561042-b07e7ab8-b0ee-4aef-b58d-4cf1f0692166.png)

Security tab in BIOS, going to Locked Setup prompts for password entry...

![image](https://user-images.githubusercontent.com/49938263/131561167-ca95dbcd-1036-47ea-b2a1-fdd1c73f90ae.png)

Detailed specs [can be viewed here](https://www.dell.com/support/home/en-us/product-support/servicetag/0-UTBNMlltUTFyLzRiTjk1enNqeURpQT090/overview).

**Comment by JonnyTech** [comment]
From previous issues: After typing your password, to accept press left CTRL key and holding this key Press Enter **twice**

**Comment by asheroto** [comment]
Hi,

Yes, I tried that. Holding Ctrl and pressing the enter key twice actually enters a character (twice). Is that the expected result?

**Comment by asheroto** [comment]
Yes, the left Ctrl key and the enter key on the laptop keyboard itself.

**Comment by JonnyTech** [comment]
Another thing that I just read: the letters are case sensitive and the numbers should be from the top of the keyboard, not the numpad, if that does not work then I am out of ideas, sorry.

**Comment by JonnyTech** [comment]
Found more tips from https://1024kb.co.nz/bios/:

1. Use a USB QWERTY keyboad.
2. When entering an Uppercase character use Caps Lock, NOT Shift.
3. Press & hold the left Ctrl key when entering the password in Dell laptops, then hit Enter twice.

**Comment by asheroto** [comment]
Thanks @JonnyTech.  Part of the issue I believe is not having a known suffix.... therefore I am trying all suffixes.  I thought that top number might be a HDD serial but I changed the HDD and that number did not change.

I will try those tips, thanks again.

**Comment by JonnyTech** [comment]
Yep, your suffix does seem new (-6EE2 according to your image). Some users have had luck by downgrading their firmware to an older version until they get a match with a known working suffix.

**Comment by asheroto** [comment]
Cool, thanks, I will try that!

**Comment by K3YL0** [comment]
> Cool, thanks, I will try that!

Did you ever get it sorted?

**Comment by asheroto** [comment]
No, but I don't have the laptop anymore, it was a client's laptop. Thanks for following up though, you can close the issue if you'd like.

**Comment by K3YL0** [comment]
> No, but I don't have the laptop anymore, it was a client's laptop. Thanks for following up though, you can close the issue if you'd like.

Ok. Not a problem, Trying to help! 🐾
