### ISSUE TITLE
none of the codes that gets generated for HGZXRY1-1D3B

### ISSUE THREAD

**Issue by XrangeViking** [bacher09/pwgen-for-bios#15]
not working for HGZXRY1-1D3B

**Comment by mikrovr** [comment]
@XrangeViking 
Or you are typing the wrong password or your keyboard is the default qwerty

**Comment by XrangeViking** [comment]
ill give it a try with another usb keyboard but tried many times in diffrent ways with same keyboard

**Comment by mikrovr** [comment]
@XrangeViking 
Post the password so I can check

**Comment by XrangeViking** [comment]
wops im sorry for making an useless issue it was just that you had to ctrl + enter and not just press enter hard to know when it accept it as a wrong code. well thanks any way for the help! 👍
