### ISSUE TITLE
Dell Latitude 3300 with E7A8 suffix

### ISSUE THREAD

**Issue by dzhigit1** [bacher09/pwgen-for-bios#153]
Requesting E7A8 suffix support.

### General information
Dell Latitude 3300 with "Bios version" 1.9.1.

### Photo
![Dell_unlock_screen](https://user-images.githubusercontent.com/75542241/142794745-4c257c16-653d-4a68-9aa4-d58499eeba15.jpg)

**Comment by bacher09** [comment]
I just added E7A8 support with ee5f3a8d0da2bc7fbacf4a307e811bb46da4fbf9 and it's already installed on [beta version site](https://beta.bios-pw.org/), you can try it. Closing now, since E7A8 already supported.

**Comment by anthenorjr** [comment]
I'm very sorry to inform it doesn't work for me on my B8TMKF2-E7A8, anyone can confirm worked for him with E7A8 prerfix?

**Comment by shiva0525** [comment]
![Screenshot_2022-01-29-05-54-52-17_86d1cf8180063029dcfbc18385c9fce5.jpg](https://user-images.githubusercontent.com/66516258/151638826-71633fc3-4dc1-4b5c-b86b-704b634d3a93.jpg) try this bro..

**Comment by dzhigit1** [comment]
> I'm very sorry to inform it doesn't work for me on my B8TMKF2-E7A8, anyone can confirm worked for him with E7A8 prerfix?

I had to press Ctrl + Enter instead of Enter for it work, as it says. Type it in several times to make sure there aren't any typos, and look carefully. Try with Enter. If it doesn't work, type it in several more times, trying with Ctrl + Enter. I don't know if E7A8 has landed in stable site yet. I used beta site, linked above, as instructed by the maintainer.

**Comment by anthenorjr** [comment]
> ![Screenshot_2022-01-29-05-54-52-17_86d1cf8180063029dcfbc18385c9fce5.jpg](https://user-images.githubusercontent.com/66516258/151638826-71633fc3-4dc1-4b5c-b86b-704b634d3a93.jpg) try this bro..

I had tried before posting, my post was a feedback about exactly this. It doesn't work for me, anyone else?

**Comment by anthenorjr** [comment]
> > I'm very sorry to inform it doesn't work for me on my B8TMKF2-E7A8, anyone can confirm worked for him with E7A8 prerfix?
> 
> I had to press Ctrl + Enter instead of Enter for it work, as it says. Type it in several times to make sure there aren't any typos, and look carefully. Try with Enter. If it doesn't work, type it in several more times, trying with Ctrl + Enter. I don't know if E7A8 has landed in stable site yet. I used beta site, linked above, as instructed by the maintainer.

Thank you man, but I did tried it several times, you can see my older posts above, I tried with multiple different keyboards and with CTRL-Enter too. And nothing worked.
