### ISSUE TITLE
Dell Venue 11 Pro 5130 Doesn't generate password

### ISSUE THREAD

**Issue by keiem** [bacher09/pwgen-for-bios#159]
### General information

* **Vendor**: DELL
* **Model**: Venue 11 pro 5130
* **Firmware version**: version A05 08/22/2013

It's a 10inch tablet.
The generator doesn't generate a password.  I didn't update the bios to be sure they didn't included extra security.

**Comment by K3YL0** [comment]
Please post your Service Tag # And I'll see what I can do. Or even someone else may help.

**Comment by keiem** [comment]
Solved, seems I needed 4 extra characters after the service tag.  The extra numbers are visible when trying to unlock the bios, first the service tag then - and the following 4.  I didn't knew that and it was not clear.  But now the bios is unlocked.
