### ISSUE TITLE
dell latitude e7440 bios password error

### ISSUE THREAD

**Issue by amsherif** [bacher09/pwgen-for-bios#17]
dell latitude e7440 bios password error #6T96j12-1f66
idont have the password

**Comment by qasimtoep** [comment]
Ebay is still a good idea to buy Dell Password for 1F66 6FF1 1D3B suffix

http://www.ebay.com/sch/i.html?_odkw=Dell+password&_osacat=0&_from=R40&_trksid=p2045573.m570.l1313.TR0.TRC0.H0.XDell+password+unlock+.TRS1&_nkw=Dell+password+unlock+&_sacat=0

**Comment by mikrovr** [comment]
Ebay is still a good idea to buy all Dell Password

http://www.ebay.com/sch/i.html?_odkw=Dell+password&_osacat=0&_from=R40&_trksid=p2045573.m570.l1313.TR0.TRC0.H0.XDell+password+unlock+.TRS1&_nkw=Dell+password+unlock+&_sacat=0

**Comment by bacher09** [comment]
I'm closing this issues since code for `1F66` series already merged.

**Comment by Shahidulalam2030** [comment]
15J4N32-1F66
