### ISSUE TITLE
Does not work and throws not defined errors.

### ISSUE THREAD

**Issue by Usalabs** [bacher09/pwgen-for-bios#18]
I tried to add the code to my web server, but somewhere along the lines java console throws out these errors:-

Uncaught ReferenceError: enterPress is not defined
    at HTMLInputElement.onkeypress (index.html:36)

index.html:38 Uncaught ReferenceError: calcPass is not defined
    at HTMLInputElement.onclick (index.html:38)

The only change I did was to rename the JS file from 'decrypt_bios.js to script-33456.js and made changes to only the one line in the index,html:-

<script type="text/javascript" src="script-33456.js" ></script>

If you want to check it out, the address for testing is:- http://home-regions.no-ip.org:12080/pwgenbios/index.html  Currently the directory index is pointing to simple.html so that I have something to use.

Once it's been fixed, the actual address would be http://my-web.no-ip.net/pwgenbios/  But I'll be changing the directory index file back to index.html

I suggest using Chrome so that the page can be right clicked and select Inspect

**Comment by bacher09** [comment]
It looks like you have no `ui.js` code and  this causes issue. Later I will add docs how to build this project.
