### ISSUE TITLE
[Dell]: [Inspiron 13 5368] [0001]

### ISSUE THREAD

**Issue by MagnaLunar** [bacher09/pwgen-for-bios#183]
### General information

* **Vendor**: Dell
* **Model**: Inspiron 13 5368
* **Firmware version**: 1.23.1
* **Service Tag**: 6H1BWB2
* **Hard Disk's Serial Number**: 50026B7783064DF8

### Photo
![IMG](https://user-images.githubusercontent.com/59935255/172144881-8dacd061-06cd-46b9-a4ec-1d2459fb3fe3.jpg)

**Comment by 1024kbdotcodotnz** [comment]
0001 suffix indicates that the BIOS Master Password option has been switched off in UEFI settings.

**Comment by MagnaLunar** [comment]
It's sad... anyway, thank you for your answer
