### ISSUE TITLE
1F5A - Dell E6410

### ISSUE THREAD

**Issue by alphaaurigae** [bacher09/pwgen-for-bios#19]
Hi,

looking for the 1F5A - Dell E6410

Regards,

**Comment by qasimtoep** [comment]
look at ebay, you will not get it here

**Comment by alphaaurigae** [comment]
dell support was very helpful on this matter, they where also surprised and kindly interested about the key ebay business ;)

**Comment by mikrovr** [comment]
@alphaaurigae 
Have you solved the key for bios?

**Comment by alphaaurigae** [comment]
@mikrovr thx, dell support reset the pass after id verification.

**Comment by orie86** [comment]
Hnfh982 service tag
Inspiron 15-3552
Trying to find code for pw-bios

**Comment by rundekugel** [comment]
I needed for new Dell Mainboard the Masterpassword 1F5A - Suffix  . tried a few things for 12 hours.
ended up here:
biospassword.eu
$5 and then it worked.
@bacher09: if I can help you coding. I'd like to do. To make decoding Masterpassword free of charge.

**Comment by moslimbios** [comment]
biosunlocker.com

Le ven. 8 févr. 2019 à 13:22, rundekugel <notifications@github.com> a
écrit :
