### ISSUE TITLE
Dell Latitude 6FF1 - Bios 1.9.3

### ISSUE THREAD

**Issue by steviehs** [bacher09/pwgen-for-bios#197]
Service Tag is CSVTVP2
Tried the -6FF1 with no success and also -BF97 with no success...
German keyboard was respected
Also tried Ctr-Enter...

Any other hints?

**Comment by aditya11ttt** [comment]
Try us keyboard

**Comment by steviehs** [comment]
of course I did :-)

**Comment by xxstasxx** [comment]
Same at 568SPC2-6FF1
