### ISSUE TITLE
Use different font for passwords 

### ISSUE THREAD

**Issue by wszak** [bacher09/pwgen-for-bios#20]
Right now some characters are indistinguishable - for example:
0 / O (zero vs capital o)
l / I (small L and capital i)
This may lead to errors when retyping the password in BIOS. 
I'd suggest using a different font for passwords displayed on the webpage.

**Comment by dandar3** [comment]
Discussed as part of issue #9 (already done for `simple.html`), I wanted to do it for the main page, will come back later if no one else does it first before I do.

**Comment by KingBonecrusher** [comment]
Try Consolas, also good to read!

**Comment by bacher09** [comment]
I'm closing this issue since code already merged in master and released.
