### ISSUE TITLE
password required for 7G9C0G2-6FF1

### ISSUE THREAD

**Issue by arungskumar** [bacher09/pwgen-for-bios#26]
Hi
Could you please help me in getting bios password for mentioned tag.
Thanks.

**Comment by mikrovr** [comment]
@arungskumar 

Input: 7G9C0G2-6FF1
Password: 35c0b0tVb32Z6ivD

3 - ( digit )
5 - ( digit )
c - charlie ( lowercase )
0 - ( digit )
b - bravo ( lowercase )
0 - ( digit )
t - tango ( lowercase )
V - VICTOR ( UPPERCASE )
b - bravo ( lowercase )
3 - ( digit )
2 - ( digit )
Z - ZULU ( UPPERCASE )
6 - ( digit )
i - india ( lowercase )
v - victor ( lowercase )
D - DELTA ( UPPERCASE )

Password is case sensitive!
Passwords are for QWERTY keyboard only (standard US)
Enter calculated password carefully, Then holding CTRL push ENTER key twice

Master Bypass Keys for other laptops? mikrovr@gmail.com

**Comment by bacher09** [comment]
6FF1 codes where added by #12.

**Comment by arungskumar** [comment]
Hi,
Again, my machine had issues and I had to reimage it. While using the
earlier password, it doen nt work any more. Could you please help me get
the latest password.
Thanks.

Regards,
Arun
