### ISSUE TITLE
Maybe i can help?

### ISSUE THREAD

**Issue by KingBonecrusher** [bacher09/pwgen-for-bios#28]
@bacher09

Hi!

Maybe i could help and provide some full flash bins from an E6410 with 1F5A bios. EC and MAIN. And also some already precalculated master passwords for 1F5A with serial number. Could this help to it working for 1F5A? 

**UPDATE:**
I have done some research, and the 1F5A bios has the same chartable like 2A7B

_"012345679abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ0"_

@A-syncritus 
I still have the list with serial numbers and already **tested and working** master passwords.

**Comment by bacher09** [comment]
Sorry for late response.

Actually it's relatively easy to extract firmware from dell's exe. But precalculated passwords are really useful thing. For example, I didn't have hardware to test most of generators present here. And precalculated passwords can help with testing.

Also, one small update. I have checked ``1F5A`` firmware  and yeah it contains many similar things with ``2A7B``. For example I have found procedure that initialize array with [these values](https://github.com/bacher09/pwgen-for-bios/blob/f6888b8872240498cbe5a7282f0a4fb30210b5b4/src/dell/encode.ts#L50). Currently I have no time to work on it further, but I think that in few months I will be able to add `1FFA` support.

**Comment by KingBonecrusher** [comment]
Hi Slava

I have access to a lot of Notebooks. I am working in a refurbishing Factory. Mostly Dell/Lenovo/Hp. I hope we can work together in the future. Iam not good at math like you, but I can support you with Firmware or Infos and testing.

I have contacted you several times in the past. You can contact me directly: mario_lange@gmx.net 

I could send also my gpg id for encrypted mailing.

Like I said I have limited access to the Dell  internal support. Let me know if you need some codes. The 1F5A stuff is maybe broken by design. We got codes and even Dell is sometimes not able to generate a working one. Happens only on 1F5A! I have also codes for the newer InsydeH20 Bios with Challengenumber.

We can also share knowledge. I can unlock apple, hp some Lenovos. Iam using a SPI Flasher normally.

Rg,
Mario

Am 16. Februar 2018 16:31:00 MEZ schrieb Slava <notifications@github.com>:
>Sorry for late response.
>
>Actually it's relatively easy to extract firmware from dell's exe. But
>precalculated passwords are really useful thing. For example, I didn't
>have hardware to test most of generators present here. And
>precalculated passwords can help with testing.
>
>Also, one small update. I have checked ``1F5A`` firmware  and yeah it
>contains many similar things with ``2A7B``. For example I have found
>procedure that initialize array with [these
>values](https://github.com/bacher09/pwgen-for-bios/blob/f6888b8872240498cbe5a7282f0a4fb30210b5b4/src/dell/encode.ts#L50).
>Currently I have no time to work on it further, but I think that in few
>months I will be able to add `1FFA` support.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bacher09/pwgen-for-bios/issues/28#issuecomment-366267596

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by KingBonecrusher** [comment]
Hi Slava

How can I contact you directly?

**Comment by bacher09** [comment]
I actually wanted to keep all usefull conversations in public (maybe they can help someone other). But I would not mind. I will respond to your email.
