### ISSUE TITLE
https://bios-pw.org/

### ISSUE THREAD

**Issue by qasimtoep** [bacher09/pwgen-for-bios#32]
You help many people to make money at ebay, so https://bios-pw.org/ should be deleted for a few weeks.
After one week, you will see who has his own generator or makes money with your knowing.

**Comment by mikrovr** [comment]
@qasimtoep
Do not humiliate yourself for people who do not have the ability to develop their own generators. There is nothing here devised by Asyncritus.

**Comment by mikrovr** [comment]
makes money with your knowing. Asyncritus???? KKKKKKKKK

**Comment by bacher09** [comment]
Please stop flooding. It isn't relevant with this project in any way. Create issue if you have found bug or have a feature request.
