### ISSUE TITLE
administrative password required for 7G9C0G2-6FF1

### ISSUE THREAD

**Issue by arungskumar** [bacher09/pwgen-for-bios#34]
administrative password required for the same system number. Could you please generate and share the same.
Thanks

**Comment by bacher09** [comment]
Have you tried to input this code to [bios-pw.org](https://bios-pw.org/) ? It have support for `6FF1`.
Does `35c0b0tVb32Z6ivD` worked for you ?

I'm closing this issue since `6FF1` is supported. Reopen it if generated code doesn't work for you.
