### ISSUE TITLE
Hdd password dell 1564

### ISSUE THREAD

**Issue by AhmedAlkhulaifi** [bacher09/pwgen-for-bios#35]
I forgot the hdd password

**Comment by bacher09** [comment]
Sorry but there is not enough information. Please read [this](http://dogber1.blogspot.com/2009/05/table-of-reverse-engineered-bios.html). Then try to generate password using [bios-pw.org](https://bios-pw.org/). If this didn't worked, fill feature request and provide your serial tag.
