### ISSUE TITLE
Password gen for Dell Latitude E6410 (suffix -1F5A)

### ISSUE THREAD

**Issue by vinyldarkscratch** [bacher09/pwgen-for-bios#46]
Hey there,

I saw an issue opened about this, specifically #19, that was closed as the user was able to get a password reset through Dell.  However, it doesn't look like there's a generator for this suffix available, and I'm unable to get assistance through Dell (as the computer's original owner is unknown).  Any chance of this being added?

**Comment by KingBonecrusher** [comment]
Hi!

I think bacher09 will add it in the next time. He is very busy at the moment. You could alternatively downgrade the bios eeprom to version A01 and this has the -2A7B suffix.

**Comment by sizious** [comment]
Even better, I've just upgraded to the `A24` revision, which is the last version available for the **E4200* and it works great! Still no password at all. So this is a real nice solution for every locked Dell with suffix `1F5A`.

**Comment by vitorio** [comment]
Perhaps different models require/don't require the admin password when upgrading the BIOS?  I also have an E6410 with suffix -1F5A, and I could not downgrade it without the administrative password, the BIOS utility prompted me for it.  I ended up paying a commercial service for a master password.

**Comment by tankren** [comment]
> I can confirm that downgrading the BIOS to an old revision **works like a charm**!
> 
> I tested with a **Latitude E4200** shipped with the `A22` BIOS revision (ending with `1F5A` suffix). It was locked with an **Admin Password**. Here is the method I used:
> 
> 1. [Download the `A03` revision from the Dell website](http://downloads.dell.com/bios/E4200A03.EXE) (the whole list of available BIOS for the E4200 is [here](http://downloads.dell.com/published/pages/latitude-e4200.html)).
> 2. Use [Rufus](https://rufus.ie/) to generate a bootable, FAT USB stick with **FreeDOS**.
> 3. Copy the `E4200A03.EXE` binary to that bootable stick.
> 4. Put the battery on your laptop and plug the power cord.
> 5. Plug the prepared USB stick to the laptop and boot from it by using the `F12` key.
> 6. From the **FreeDOS** prompt, type `E4200A03` and hit `<Enter>`.
> 7. The flash program begins. **Just wait.**
> 8. After rebooting, enter to the BIOS. The suffix will be `2A7B` now!
> 9. Generate the password from the website.
> 10. In the BIOS, enter the password `Dell from serial number`.
> 
> In my case, I used this master password to clear the **Admin Password**. So go to that section and in the `Old password` field, just enter the generated password again. Leave the `New password` fields empty. Please also note that the laptop I just bought was coming without hard drive.
> 
> Also, **please note the keyboard layout used in BIOS is the US one**, in all the cases! (`QWERTY`).

hello,
    Is password needed to upgrade/downgrade the BIOS by this way? thx

**Comment by bacher09** [comment]
Done in 2c87bd691e74cfd9ee9718a37a420b989aa22740.
