### ISSUE TITLE
What abount newer Dell laptops from 2017 or 2018 for example 7290 / 7280?

### ISSUE THREAD

**Issue by darkKyle** [bacher09/pwgen-for-bios#48]
What abount newer Dell laptops from 2017 or 2018 for example 7290 / 7280?

The last 4 letters of the code not listed on the site - so dont work.
any update around?

**Comment by basemabd** [comment]
Dell 7390 6CY4QN2-BF97

**Comment by moslimbios** [comment]
www.biosunlocker.com

**Comment by basemabd** [comment]
Idont trust you


في جمعة، ٢٨ كانون الأول، ٢٠١٨ في ١١:٤٦ م، كتب moslimbios <
notifications@github.com>:

**Comment by kool4aid** [comment]
I hate this laptop now Im gettin HDD#***S3PY9Q03-6FF1.what does all this mean

**Comment by qasimtoep01** [comment]
> 
> 
> I hate this laptop now Im gettin HDD#***S3PY9Q03-6FF1.what does all this mean

Password is: p5fUGx5zpZ2Mpvet

**Comment by kool4aid** [comment]
Thank you sir I really appreciate it

**Comment by basemabd** [comment]
Dell 7390 iwant password security manager how open that

**Comment by basemabd** [comment]
Iam open that dell 7390

**Comment by basemabd** [comment]
Open 40$ my laptop dell Latitude 7390 iam so happy

**Comment by qasimtoep01** [comment]
too  much.

https://www.ebay.com/sch/i.html?_from=R40&_trksid=m570.l1313&_nkw=bf97+password&_sacat=0

**Comment by Darkorkid** [comment]
Pls Dell latitude 7490,   4GR93X2-BF97

**Comment by bacher09** [comment]
BF97 already supported in beta, in few days it will be available on main site.
