### ISSUE TITLE
Hp bios disable code 60640577

### ISSUE THREAD

**Issue by Somarriba1982** [bacher09/pwgen-for-bios#50]
I am not able to unlock my HP using the code generated.

Disable code 60640577

Thanks

**Comment by Somarriba1982** [comment]
Plz help guys. I cannot access to my laptop yet.

**Comment by qasimtoep01** [comment]
password is: 75728579

**Comment by qasimtoep01** [comment]
are you sure your Disable code is  60640577 and not i60640577 ????

**Comment by Somarriba1982** [comment]
It had the "i" at the beginning but the online calculators shown invalid every time at included it.

Unexpectedly the pc is giving me a totally different system disable code right now. Here it is
i 84987200

**Comment by Somarriba1982** [comment]
I can send you a screenshot right now if you like

**Comment by qasimtoep01** [comment]
go to ebay, online calculator can´t do it for you

**Comment by Somarriba1982** [comment]
Can you unlock it for me? I can make the payment through paypal or any other money transfer. I do not trust at ebay dudes. Even I know that you could be one. :(

**Comment by qasimtoep01** [comment]
https://www.ebay.com/itm/HP-bios-power-on-password-8-digit-code-starting-with-i-like-i-12345678/143073551278?hash=item214fd923ae:g:JaoAAOSwAx9cKcVj:rk:11:pf:0

**Comment by moslimbios** [comment]
https://www.ebay.com/itm/323574422646

Le sam. 5 janv. 2019 à 19:41, qasimtoep01 <notifications@github.com> a
écrit :

**Comment by EvanCarroll** [comment]
This issue is a dupe of https://github.com/bacher09/pwgen-for-bios/issues/52

**Comment by bacher09** [comment]
Closing as duplicate, also this should be already supported.
