### ISSUE TITLE
HP Stream, halt code [ i 85070929 ]

### ISSUE THREAD

**Issue by paul1149** [bacher09/pwgen-for-bios#52]
I've got an HP Stream 11-y010wm with locked bios. The presence of the "i" before the 8-digit numerical code indicates a different locking system than HP used previously. The halt code is static - it doesn't change with each failed attempt. What's more, there are services out there that claim to be able to crack the code, with prices ranging from $25 to double that.

I've tried a few things from the site, like holding down the ctrl key, and I've tried pulling the cmos battery and doing a power drain, but nothing worked. Nor did I find any schematic online that might indicate jumpers on the motherboard. Does anyone have any insight into this? Thanks.

**Comment by EvanCarroll** [comment]
I'm in the same boat with this laptop `i 81422852`. It would be great if he we had some prior keys and values to test a valid keygen if one is ever created.

**Comment by moslimbios** [comment]
www.biosunlocker.com/prices

**Comment by Rdp3389** [comment]
seems like in the newer BIOS/CMOS the passwords are stored in NVRAM and are prone to battery removal and other methods from the past. 
also, the pwgen script is no longer relevant.

I've collected some of the **working** codes from **HP forum** - just in case it will help someone to find the new salt or to figure our the new algorithm somehow...

# Lower case i
i 70412809 = 47283646 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/Administrator-or-power-on-password/m-p/7035999#M160957 )
i 76205377 = 41898738 15-Ab254sa ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/administrator-password-for-bios/m-p/7036053#M160962 )
i 52669168 = 65436527 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/System-Disabled-i-52669168/td-p/6589533 )
i 58828448 = 65477807 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/Re-Need-boot-unlock-code-System-Disabled-code-is-i-82498067/m-p/7037464#M161051 )
i 62996480 = 55507825 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/Bios-Password/m-p/7034248#M160859 )
i 51120876 = 66775639 ( https://h30434.www3.hp.com/t5/Notebook-Software-and-How-To-Questions/HP-stream-11-admin-password-error-code-i51120876/m-p/7034314#M257024 ) 
i 69779941 = 54526704 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/bios-and-power-on-password-needed-system-disabled-code/m-p/7030930#M160645 )
i 75582785 = 42313120 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/Re-HP-15-bs005nw-Notebook-bios-password-reset/m-p/7032254#M160727 )
i 52214872 = 65889633 ( https://h30434.www3.hp.com/t5/Notebook-Operating-System-and-Recovery/System-disabled-stream-14/m-p/7030298#M556034 ) 
i 77319488 = 40986827 ( https://h30434.www3.hp.com/t5/Notebook-Operating-System-and-Recovery/System-disabled-i-77319488/m-p/7030025#M556014 )
i 68852353 = 55443712 ( https://h30434.www3.hp.com/t5/Notebook-Operating-System-and-Recovery/BIOS-Master-Key/m-p/7029787#M555984 )
i 59170869 = 64725626 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/Re-BIOS-ask-administrator-password/m-p/7029087#M160540 ) 
? 51974384 = 44652900 ( https://h30434.www3.hp.com/t5/Notebooks-Archive-Read-Only/Re-Hi-I-have-an-Hp-Pavilion-x360-and-I-forgot-my-Bios-power/m-p/7032918#M3146179 )
i 63121056 = 54774419 ( https://h30434.www3.hp.com/t5/Business-Notebooks/system-disable-i-63121056/m-p/7027320#M154053 )
i 68105474 = 55798831 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/BIOS-password-reset/m-p/7021474#M160061 )
i 87267970 = 10836735 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/I-need-bios-administrator-password-for-my-Hp-notebook-15/m-p/7019923#M159943 )
i 93641394 = 04454731 ( https://h30434.www3.hp.com/t5/Notebook-Operating-System-and-Recovery/Administrator-power-on-password/m-p/7019332#M555243 ) 
i 67943987 = 50552728
i 92709523 = 05596962
i 86013615 = 11682050
i 97341105 = 00954540
i 52798248 = 65507607
i 50477165 = 67226520
i 61829943 = 56476702
i 69740510 = 54555955
i 81422854 = 16273611
i 84094334 = 13609771
i 58205255 = 65898610
i 77122234 = 40773671
i 58044249 = 65659606
i 59755840 = 64548605
i 85871936 = 12424779
i 67292480 = 50803825
i 59146240 = 64757605
i 60227584 = 57876921
i 68701505 = 55594940
i 68258503 = 55847942
i 62433029 = 55262466
i 63467458 = 54236817
i 57596608 = 60307047
i 51596608 = 66307047

notice the last two - only a single digit is different on both sides!

# Upper case i
I 51085312 = 44983934 	HP 15-ac123TX  ( https://h30434.www3.hp.com/t5/Notebooks-Archive-Read-Only/Re-BIOS-PASSWORD-RESET-FOR-HP-15-AY052NX/td-p/6775467 )
I 86013615 = 39971231 	Pavilion X360-M1
I 59170869 = 46858269 ( https://h30434.www3.hp.com/t5/Notebook-Boot-and-Lockup/Re-BIOS-ask-administrator-password/m-p/7029087#M160540 )

**Comment by securityresearchlab** [comment]
> I've got an HP Stream 11-y010wm with locked bios. The presence of the "i" before the 8-digit numerical code indicates a different locking system than HP used previously. The halt code is static - it doesn't change with each failed attempt. What's more, there are services out there that claim to be able to crack the code, with prices ranging from $25 to double that.
> 
> I've tried a few things from the site, like holding down the ctrl key, and I've tried pulling the cmos battery and doing a power drain, but nothing worked. Nor did I find any schematic online that might indicate jumpers on the motherboard. Does anyone have any insight into this? Thanks.

Hi Paul, please try this code: 12625766. Thanks.

**Comment by tgun** [comment]
@Rdp3389 nice research!!
It looks like the whole thing is a one to one mapping that doesn't change (at least for the lowercase i codes)

Using the extensive table you provided above I generated this; You can use this to convert an i code into an unlock code. The only digit I didn't get the complete set for is the first digit, but you may be able to extrapolate out what the value would be based on the pattern from the ones we do have.

`1 digit:
    5 => 6
    6 => 5
    7 => 4
    8 => 1
    9 => 0

2 digit: =>>>> DONE
    0 => 7
    1 => 6
    2 => 5
    3 => 4
    4 => 3
    5 => 2
    6 => 1
    7 => 0
    8 => 5
    9 => 4

3 digit: =>>>> DONE
    0 => 8
    1 => 7
    2 => 8
    3 => 9
    4 => 2
    5 => 3
    6 => 4
    7 => 9
    8 => 4
    9 => 5

4th digit: =>>>> DONE
    0 > 9
    1 > 8
    2 > 7
    3 > 6
    4 > 5
    5 > 4
    6 > 3
    7 > 2
    8 > 1
    9 > 0

5th Digit: =>>>> DONE
    0 > 5
    1 > 4
    2 > 3
    3 > 2
    4 > 9
    5 > 8
    6 > 7
    7 > 6
    8 > 7
    9 > 6

6th digit: =>>> DONE
    0 > 4
    1 > 5
    2 > 6
    3 > 7
    4 > 8
    5 > 9
    6 > 0
    7 > 1
    8 > 6
    9 > 7

7th digit:=>>>> DONE
    0 > 4
    1 > 5
    2 > 6
    3 > 7
    4 > 0
    5 > 1
    6 > 2
    7 > 3
    8 > 2
    9 > 3

8th digit: =>>>> DONE
    0 > 5
    1 > 4
    2 > 3
    3 > 2
    4 > 1
    5 > 0
    6 > 9
    7 > 8
    8 > 7
    9 > 6`

**Comment by Rdp3389** [comment]
@tgun WOW, that's REALLY cool. how didn't I though of that?
I've converted your idea [into a script](https://gist.github.com/Rdp3389/4731d2d85cc6a8bad03182889240b7ca), and it does work correctly for most of the items.

But:
1. There are few wrong cases:

- ERROR: INVALID result for input i69779941 is 54926704. but expected 54526704
- ERROR: INVALID result for input i92709523 is 05996962. but expected 05596962
- ERROR: INVALID result for input i86013615 is 11882050. but expected 11682050
- ERROR: INVALID result for input i52798248 is 65907607. but expected 65507607
- ERROR: INVALID result for input i69740510 is 54955955. but expected 54555955
- ERROR: INVALID result for input i58044249 is 65859606. but expected 65659606
- ERROR: INVALID result for input i84094334 is 13809771. but expected 13609771
- ERROR: INVALID result for input i59755840 is 64948605. but expected 64548605
- ERROR: INVALID result for input i68701505 is 55994940. but expected 55594940

2. the script does not support 'I' (capital i)

thank you!

**Comment by linelow** [comment]
Man I can honestly say "I love you man" I have been trying to deal with this code for days. I was going to go and buy an EEPROM reader, You are so freakin awesome! Thank You

**Comment by leosvany888** [comment]
Hi. I have an hp stream laptop with a power on password. The system disable code is (i50913144). I needed de password for this code. Can somebody help me please?

**Comment by Rdp3389** [comment]
@leosvany888 
1. go to this page - https://repl.it/repls/SourFuchsiaBrowser#main.py
2. Enter your code in the 5th line. 
   be sure to use the right capitalization of the first letter ('i' or 'I')...
3. click on 'run'
4. the result will appear on the right side

![HowToUse](https://user-images.githubusercontent.com/53836009/83852241-2b8ff900-a71c-11ea-898d-0380b1553f26.png)

**Comment by bacher09** [comment]
This already supported in 1580bf4ac103e54b3bd5741556f7f795e0ddecd1 (both uppercase and lowercase variants) and available on [beta site version](https://beta.bios-pw.org).

I also just updated [main site](https://bios-pw.org/) version (so it should be working there too)

**Comment by bacher09** [comment]
Btw @Rdp3389 thanks for collecting test data, I used it a test cases.
Also wanted to say that `? 51974384` is an uppercase variant.
