### ISSUE TITLE
need bois password

### ISSUE THREAD

**Issue by mezdah** [bacher09/pwgen-for-bios#55]
can any one help me. ican't install windows in my pc
DEL  FY49D12-1F66

**Comment by basemabd** [comment]
6CY4QN2-BF97

**Comment by basemabd** [comment]
Dell BIOS password 6CY4QN2-BF97 iwant key bios

**Comment by moslimbios** [comment]
biosunlocker.com

**Comment by moslimbios** [comment]
biosunlocker.com

**Comment by moslimbios** [comment]
doesnt accept paypal ?  who told u that ? biosunlocker.com on website and
ebay too ...

Le mer. 26 déc. 2018 à 18:22, qasimtoep01 <notifications@github.com> a
écrit :

**Comment by qasimtoep01** [comment]
however, your prices are a joke

**Comment by qasimtoep01** [comment]
if you need a BF97 password, just search for laptopfreaker at ebay. Not needed to search in Maroscco

**Comment by moslimbios** [comment]
ohhhh...   say thaaatt  ... u r  racist  ...   soo ok ...  u r ill ... hope
u to recover soon

Le mer. 26 déc. 2018 à 18:52, qasimtoep01 <notifications@github.com> a
écrit :

**Comment by qasimtoep01** [comment]
i´m no racist, I have many friends from Marocco ;)
