### ISSUE TITLE
Acer aspire 5 a515-51-56k6 suggested password does not work

### ISSUE THREAD

**Issue by LukeDaniel16** [bacher09/pwgen-for-bios#59]
I put the code that shows on the BIOS lock screen, but the site gives me a password from a Compaq Hp, which does not work in any way on the model quoted

**Comment by LukeDaniel16** [comment]
My code is: 1102866946

**Comment by Halamix2** [comment]
See #42, new unlock mechanism haven't been cracked yet

**Comment by mandaputtra** [comment]
Here my BIOS password promt it may help maybe.

1768979253
1422647124

I fucked up forgot my pass, now I can't uninstall windows :( to switch to SSD

**Comment by mandaputtra** [comment]
Got damnit why the bios key always changed!

**Comment by mandaputtra** [comment]
DOnt update your BIOS there is a bug when the BIOS updated master key do change!

**Comment by mandaputtra** [comment]
I'm just recovered my BIOS i dont had to pay anything, but sorry I dont have the code :(

**Comment by bacher09** [comment]
This should be already supported.
