### ISSUE TITLE
Latitude 5591

### ISSUE THREAD

**Issue by RiPr315** [bacher09/pwgen-for-bios#62]
Express service code-34260043466
FQLJMQ2-BF97 I've went thru every code you gave posted on here for Dell and I'm getting nowhere!!! Please, is there any code that will unlock this computer without having to purchase. I already spent too much on this laptop and I haven't got to even use yet. Please help me.

**Comment by bacher09** [comment]
BF97 already supported in beta, in few days it will be available on main site.
