### ISSUE TITLE
HP Notebook - 15-ay503tx (Suggested Codes not working)

### ISSUE THREAD

**Issue by rp181135198** [bacher09/pwgen-for-bios#69]
BIOS code generated = [i 85760641]

I got these codes..

![IMG_20190810_105134](https://user-images.githubusercontent.com/49446878/62817957-06167b00-bb5d-11e9-8971-43b96232c792.jpg)

Code length is too long in the above screenshot.. NOT WORKING.

![IMG_20190810_105203](https://user-images.githubusercontent.com/49446878/62817959-0c0c5c00-bb5d-11e9-93de-54f347fecb8f.jpg)

Both codes from the second screenshot is not working too..

Help me with this please..

**Comment by AKhilGarg91** [comment]
Did u get any solution? I am also stuck with it.

**Comment by rp181135198** [comment]
@AKhilGarg91 
Not yet.. I just wanted to change the Boot-order from BIOS mode to make Linux the default in my Dual boot laptop.. 

But, there is an option to shift to "[Boot Menu](https://www.windowspasswordsreset.com/blog/boot-menu-key-and-bios-key-for-hp-laptop-and-desktop/)" by pressing **"F9"** key when you start your laptop.

It may help you if you wanted to do the same.

**Comment by tgun** [comment]
try:
12935004

**Comment by mohamedxp** [comment]
key 12535004

**Comment by bacher09** [comment]
This already implemented in 1580bf4ac103e54b3bd5741556f7f795e0ddecd1.
