### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by jtagcat** [bacher09/pwgen-for-bios#71]
Hey @bacher09, are you still maintaining this project?
If not, I could take the project over and maintain it myself, as I have found it a valuable resource, saving hundreds of computers from trash.

**Comment by bacher09** [comment]
Yes I am, In fact I'm currently working on major upgrade (mainly support of other firmware).
I'm currently have not enough of time to respond to everyone in issues, but it still maintained and working.

**Comment by jtagcat** [comment]
I'll just mention that I am sitting next to a few computers. If there is any need for resources.
![IMG_20190814_143613](https://user-images.githubusercontent.com/38327267/63168010-783a0480-c022-11e9-9b64-400c061ecccf.jpg)
:)

**Comment by jtagcat** [comment]
I'll just mention that I have a [wide selection of laptops](https://sh.c7.ee/DsCui/IMG_20190814_143613.jpg), if there is need for BIOSes. ;)

**Comment by bacher09** [comment]
It's nice, but to be honest I'm working on making tests in emulated environment, in using tools like  [unicorn engine](https://www.unicorn-engine.org/) and [ESIL](https://radare.gitbooks.io/radare2book/disassembling/esil.html) from radare2. Although some of them have bugs that affect result.
