### ISSUE TITLE
Dell Vostro 3546

### ISSUE THREAD

**Issue by Morgy93** [bacher09/pwgen-for-bios#74]
Hello,

my service tag is 7F5F832 and I tried with several suffix, but cannot find a working password.

Any help?

**Comment by jtagcat** [comment]
Can you get to the bios?

**Comment by Morgy93** [comment]
@jtagcat 
Where do I get the serial number from?
I cannot access the laptop at all and on the back of the laptop there's only the service and express service number.
Is it printed on the mainboard somewhere or something like that?

**Comment by jtagcat** [comment]
From the bios or from the back (if it's scraped off, inside the casing as well)

**Comment by Morgy93** [comment]
@jtagcat I cannot access the bios and on the back there's only: 
![image](https://user-images.githubusercontent.com/7961978/64156084-6636cf00-ce34-11e9-842c-1a71f0b6d4d0.png)

**Comment by jtagcat** [comment]
First what does show up when you try entering the bios?
Can you make a picture of it or do you see a number anywhere with -xxxx at the end of it? (f2 menu, f12 menu).
If all else fails, can you boot to usb, boot to lan, boot to internal hdd?

**Comment by bacher09** [comment]
@jtagcat It's another firmware and it's isn't currently supported by this tool.

**Comment by Morgy93** [comment]
@bacher09 Thanks for clarification! Still much appreciated work you've all done here.

Maybe any hint "where I could go next"?

**Comment by jtagcat** [comment]
Oh, didn't have the idea to look if it's compatible first :man_facepalming: 
Look in the user/maintenance manual online, look for cmos reset options, it might have a jumper or something, removing the cmos battery for some time might work.
If you can verify your ownership of the device, dell should be able to reset all of their computers.
Otherwise the hardware option.

**Comment by PityuFly** [comment]
how do you run the program in a local computer?
I start index.html from html folder, insert the code and don't get response?

**Comment by Morgy93** [comment]
I got my password from https://biospassword.eu/dell-without-suffix - worked flawlessly

Thanks anyway for this great project!
