### ISSUE TITLE
Algorythm for -1D3B

### ISSUE THREAD

**Issue by yannpub** [bacher09/pwgen-for-bios#8]
Hello,

I tried the algorithm for Dell -1D3B password creation, but it seems not to create valid passwords.

Thanks
Yann

**Comment by authorfunction** [comment]
Yes, I tried it as well. Tested all the generated passwords– "Incorrect password" each time. (Used simple.html, the other interface didn't seem to work)

**Comment by authorfunction** [comment]
Sorry – I take that back! Did some research and found that you are supposed to *hold ctrl while pressing enter twice* after entering the password. :) Thnx yannpub

**Comment by mariogamer2** [comment]
How? I do not understand that.

**Comment by authorfunction** [comment]
@mariogamer2, like this: (1) open simple.html in a browser; (2) generate the unlock-password by entering -1D3B code; (3) enter the generated password in bios pw-dialog on latop; (4) hold the control-key and press enter twice. 

This procedure worked on my Dell-laptop. Can’t help you any more if yours is different.

**Comment by mikrovr** [comment]
Today, I will release my codes! 
1F5A, 1F66, 3A5B, 6FF1, without any suffix

**Comment by yannpub** [comment]
I did some extra tests, and now confirm the algorithm works. My issue was a stupid one : in the code, I read small l (L) instead of cap i (I) : l vs I.
maybe in the page layout, it would be great to force a font that shows a difference between the two, to avoid misreading.
Thanks !

**Comment by dandar3** [comment]
Fixed width (mospace fonts) usually are designed to avoid those kind of issues - l vs i, 0 vs O etc. A bunch of ready to use web fonts here: https://fonts.google.com/?category=Monospace

Also a text to speech web widget next to the text would help too, e.g. https://responsivevoice.org/

**Comment by qasimtoep** [comment]
thank you @dandar3, for changing the font. Now it is much more easier to calculate and sell the correct password from https://bios-pw.org/ :)

**Comment by mikrovr** [comment]
@gasimtoep
You're still an idiot!:(((

**Comment by qasimtoep** [comment]
@mikrovr you are still nothing :)
