### ISSUE TITLE
HELP! BIOS PASSWORD FOR ACER ASPIRE 5 A515-43/A515-43G

### ISSUE THREAD

**Issue by theresaamouzou** [bacher09/pwgen-for-bios#84]
Hi Guys !! 

I followed some instructions on YouTube, entered the key it gave me into the Bios code and I got back a password but it doesn’t work , apparently it’s for HP laptops. 

So if there’s anyway I can get a code for the Acer 5 laptops I would be so appreciative . I don’t have the money to spend to get the manufacturers to fix it for me when I can do it myself with all your help of course:) ! Please and thank you .

**Comment by srinivas12504** [comment]
Same here as well. Mine is an acer aspire 5 A515-54G, the key is a 10 digit one.....

**Comment by cgmafia** [comment]
Same here with Acer Nitro 5, generated key doesn't work

**Comment by ankitpal35** [comment]
Please check out this repository it's working for many user's scroll to the bottom of the comment and enter  
:https://github.com/bacher09/pwgen-for-bios/issues/42
and 
https://github.com/let-def/insydious

**Comment by bacher09** [comment]
This should be already supported in 327fa5f8154e2c3d9f36b63f892d87685161c3b3 and available on main site.
