### ISSUE TITLE
Generated code didn't work for HP EliteBook 820 g2

### ISSUE THREAD

**Issue by Temu4** [bacher09/pwgen-for-bios#85]
Unfortunately, code didn't work for my HP EliteBook 820 g2.
It will be great if you can help. Thank 🙏

**Comment by bacher09** [comment]
Sorry for my late response, this should be already implemented in 1580bf4ac103e54b3bd5741556f7f795e0ddecd1, unless your laptop is using other algorithm in that case reopen issue and provide more information.
