### ISSUE TITLE
bios password for HP Envy 15-k013tx

### ISSUE THREAD

**Issue by handsome-pk** [bacher09/pwgen-for-bios#88]
Dear developers,

I am using HP ENVY 15-K013TX LAPTOP,  i received CMOS checksum message few days back, had bios password check enable on boot, after several attempts of diagnostic a disabled my boot password, but unfortunately it didn't work and my password was reset and still receiving enter admin password on boot. So need assistance to reset boot pass and receivng error code "i 62996480" after 3 attempt and could proceed forward.

My email is shafiq.hims@gmail.com

**Comment by bacher09** [comment]
This already implemented in 1580bf4ac103e54b3bd5741556f7f795e0ddecd1.
