### ISSUE TITLE
BIOS password for Acer Spin SP314-51

### ISSUE THREAD

**Issue by dantfusie** [bacher09/pwgen-for-bios#92]
I did tried to use the biospw website and the beta version (which works on 8 digit unlock password only, I have 10 digits), but it dosen't work. 
I had some issues with ubuntu's mokutil and shim, trying to reinstall Windows back. Spitted out 'security boot fail' prompt, the only way to fix it is too disable secure boot, but I somehow have a password lock. BIOS version is InsydeH20 v1.14, Rev 3 (before installing ubuntu couple of days ago).
Did tried to remove the CMOS battery and let it sit overnight, resetted the BIOS settings but did NOT cleared the password, and it will change the unlock password everytime you disconnect the CMOS, this time the code is this.

Unlock Password is 2014593161

Thanks.

**Comment by Evernow** [comment]
Shouldn't have gotten a laptop man

**Comment by bacher09** [comment]
This should be already supported in 327fa5f8154e2c3d9f36b63f892d87685161c3b3 and available on main site.
