### ISSUE TITLE
Implementation of 10 digits unlock code

### ISSUE THREAD

**Issue by let-def** [bacher09/pwgen-for-bios#95]
Hello,

I have implemented the derivation scheme for Acer/Insyde 10 digits unlock codes:
https://github.com/let-def/insydious

You are welcome to reuse my code, or simply import the `deriv.js` module which exports an `unlock(string):string` function. (I don't use Typescript and I am not familiar with JS toolchains, so I won't be able to do a proper PR)

Also: please comment if it worked or did not work for your code, there are six variants of the algorithm and I can only be sure that the one my computer had work.

**Comment by bacher09** [comment]
Hi, if you want to make a PR I can help you and typing system in TypeScript in a way very similar to the one in Haskell or Ocaml (in it's own way).

Now regarding the code, I usually try to undo optimizations that was done by the compiler (for example I roll back unrolled loops, etc) so resulted code is small (and probably easy to understand), also I try to name thing right.

For example you [code](https://github.com/let-def/insydious/blob/master/deriv.ml#L59) has an array  `pass_1_secret_1` which is in fact looks like identical to [SHA256](https://en.wikipedia.org/wiki/SHA-2#Pseudocode) ([js implementation](https://gist.github.com/DanBrothers/0fad219095015cf3633d09e9ab979ce9#file-sha-256-js-L42)). And it looks like it reimplements other parts of Sha256 as well.

**Comment by dantfusie** [comment]
I had tried, and it works! (Finally!)

**Comment by let-def** [comment]
@bacher09 Thanks for looking at the code. I have annotated common constructions (you are right that the first pass looks suspiciously like sha256, but I don't have the time to properly test that). Similarly, I have identified an occurrence of Rijndael s-box in the second pass, so it might be doing something AES-ish and CRC64 in the third one.

**Comment by let-def** [comment]
I don't want to spend more dev time on that, I am not interested in doing a typescript port. But feel free to do that.
I just want people to be able to use their computer, and I think that is achieved with the JS webpage.

**Comment by LHCortez** [comment]
Tested on my Acer laptop and it worked!
Thank you so much, you just saved me 20 bucks.

**Comment by pixlmaster** [comment]
It worked for me.
Thanks for working on this.

**Comment by guserlangga** [comment]
please tell me how to use it, or someone can help me to get my bios password? please help

**Comment by m4ccim** [comment]
Thanks, it worked! I happend to stuck with basic touchpad just because of the locked bios.

**Comment by m4ccim** [comment]
@guserlangga you go to the link. A bit lower you see Readme's text. The first line is the link to unlocker site.

**Comment by guserlangga** [comment]
> @guserlangga you go to the link. A bit lower you see Readme's text. The first line is the link to unlocker site.

THANK YOU SO MUCH ALL, it worked !!!!!!!

**Comment by VorticA** [comment]
This is it! It worked on my A715-71G! Spread the word! Spread the word!!!

**Comment by ironforge07** [comment]
I used this on my Acer Nitro 5 ,you’re a lifesaver.

THANK YOU!!

**Comment by woutershep** [comment]
Worked like a charm on my Acer Predator Helios 500. Great work let-def.

**Comment by ariffidaali** [comment]
Yes finally it worked for my Acer Predator Helios 300 (2019). Thanks sooooo much!!

**Comment by FeralBytes** [comment]
Thank you so much. It worked and unlocked the bios on my Acer Aspire 3.

**Comment by bacher09** [comment]
@let-def can you specify model of your laptop, I'm going to work on this, but to verify algorithm I need to know model (and firmware version).

**Comment by let-def** [comment]
@bacher09 Sure. It is an Acer Swift 3 SF314-56. The problem appeared on BIOS v1.06. I thought that upgrading the BIOS would solve the problem, so I updated to BIOS v1.14. Because the problem persisted, I started working on unlock code from this version (though feedback I got since that time since to indicate that it works with other ACER models, as long as the code is 10 digit).

**Comment by bacher09** [comment]
Thanks @let-def, I asked because I tested it against [these codes](https://github.com/bacher09/pwgen-for-bios/issues/42#issuecomment-590577305) and for some of them results matches, but for some other it isn't. Also, for verifying algorithm I often use trick with [unicorn engine](http://www.unicorn-engine.org/) which allows to calculate code using original firmware.

**Comment by let-def** [comment]
The code is the output of a crc 64, a 64-bit number written in hexadecimal form.
I suspect that the codes from your listing that are not valid hexadecimal numbers are garbage.

**Comment by bacher09** [comment]
Maybe (but I doubt it), or maybe there is another algorithm also. Anyway, I'll try to find this out.

**Comment by mjalil2** [comment]
> Thanks @let-def, I asked because I tested it against [these codes](https://github.com/bacher09/pwgen-for-bios/issues/42#issuecomment-590577305) and for some of them results matches, but for some other it isn't. Also, for verifying algorithm I often use trick with [unicorn engine](http://www.unicorn-engine.org/) which allows to calculate code using original firmware.

all those code are tested from another customers on somewebsite offer for asking payment 2 of those code not right but the others all right and worked

**Comment by let-def** [comment]
@bacher09: I used [efiperun](https://github.com/jethrogb/uefireverse/tree/master/efiperun) to map the derivation code from bios v1.14 in a unix process. I manually patched the allocation routine as this was the only external call (I have the address somewhere in my notes if you want). Once that was done, I had a function to check my output against.

**Comment by Sithamfr** [comment]
Hello, first of all, thank you for your great job ! I tried to use your code with my unlock code of bios but it didn't work. I'm also on Acer Swift 3 SF314-56. If you need other info I'm available and I will follow that discussion with hope !

**Comment by let-def** [comment]
@Sithamfr Sure. What is the code and what is the bios version?

**Comment by Sithamfr** [comment]
Thanks. The code is 1592975906 with version 1.13. 
Your code is rendering 040ba75842b72edf for that.

**Comment by let-def** [comment]
I confirm that this is the correct code for bios v1.14 (worst case: if you can still boot to windows, you can update the bios from there)

**Comment by Sithamfr** [comment]
In fact, I installed Ubuntu 18.04 on it and removed Windows 10. And today it won't start anymore after a power failure.
Is there a way to update the bios with a Live USB ? Or to get the key without update the bios ?

**Comment by let-def** [comment]
I just checked BIOS version 1.13 and the password module did not change so the code should work on your computer too.
Try inputting the password with an external keyboard: I experienced weird behavior from the keyboard, sometime typing with "numlock" set. It is safer if you can use a non-laptop keyboard to input the key.
Alternatively, another power failure will produce a new unlock code. You might have more luck this time :P.
Since the password module is the same, I don't think updating the BIOS will help. However it will likely produce a new unlock key. Unfortunately, I did not find another way than booting on windows to update the bios. (ACER...)

**Comment by xexov37456** [comment]
Just opened an account to show appreciation for your work !
The conventional bios-pw codes didn't work for me, acer service center couldn't care less and your code worked wonders, and for free ! Thanks you so much again !

**Comment by spalding99** [comment]
Was excited to find this page after months of being locked out of the BIOS on my  Acer Spin 3.
Entered the 10 digit code and received the following: af37ef70753648a1.
But, when I try to insert it into the bios password box, it stops accepting input after 10 asterisks.
Any ideas?
TIA

**Comment by Enkey404** [comment]
I confirm that this is the correct, The code is 1838342692  Im using Nitro AN515-52 Bios V1.22
Your code is rendering 918369b734561239 for that.
Thanks for help us

**Comment by bacher09** [comment]
I added support for this in 327fa5f8154e2c3d9f36b63f892d87685161c3b3. Regarding AES, it uses absolutely standard AES-128-ECB encryption, but has some custom stages before this.

**Comment by Sithamfr** [comment]
After a long time without doing nothing, I come back with good news. I thank you a lot because I succeeded. I had to type your unlock you like if my keyboard was QWERTY and it works with your code. Thank you again !

**Comment by spalding99** [comment]
Could you explain this, **"I had to type your unlock you like if my keyboard was QWERTY"** , please?

**Comment by Sithamfr** [comment]
I'm french so my keyboard is AZERTY. When I typed the code and succeeded, I typed on my keyboard like if it was a QWERTY ("a" become "q"...)
